name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Type check
      run: |
        cd frontend
        npm run type-check || true

    - name: Lint
      run: |
        cd frontend
        npm run lint || true

    - name: Build
      run: |
        cd frontend
        npm run build
